baseURL = "https://foodvib.es/"
languageCode = "en-US"
title = "Food Vibes - Cookbook and Recipes at foodvib.es"
disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = true

[params]
  description = "Food Vibes: Cookbook and Recipes for West Coast and Island lifestyles. Casual California and Hawaiian inspired cuisine. Good food. Strong drink."
