baseURL = "http://foodvib.es/"
languageCode = "en-US"
title = "foodvib.es"
googleAnalytics = "UA-99123656-4"

[taxonomies]
category = "categories"

[params]
meals = ["breakfast","lunch","dinner"]
extras = ["sweets","fiddles","drinks"]
